name: Doxygen
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  doxygen:
    name: DoxyGen
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: 'docs/Doxygen'
